# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'invalid.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
<<<<<<< HEAD
        MainWindow.setObjectName("QTπ - Base")
        MainWindow.resize(100, 95)
=======
        MainWindow.setObjectName("QTpi - Base")
        MainWindow.resize(168, 95)
>>>>>>> ca39e9fcffd0480749ce495ca4b6ba6810ae02e1
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 121, 16))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 168, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
<<<<<<< HEAD
        MainWindow.setWindowTitle(_translate("QTpi - Base", "QTπ - Base"))
=======
        MainWindow.setWindowTitle(_translate("QTpi - Base", "QTpi - Base"))
>>>>>>> ca39e9fcffd0480749ce495ca4b6ba6810ae02e1
        self.label.setText(_translate("QTpi - Base", "Invalid credentials!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
